### ISSUE TITLE
All the configuration and guides are gone

### ISSUE THREAD

**Issue by shloakvatsyayan** [YoSoyVillaa/next-litebans#1]
Title says it all.

**Comment by YoSoyVillaa** [comment]
Hi!, I will need you to explain a little bit more what do you mean. You can check the configuration at [`config/site.ts`](https://github.com/YoSoyVillaa/next-litebans/blob/main/config/site.ts), and the guide for the installation in the [repo's README](https://github.com/YoSoyVillaa/next-litebans/blob/main/README.md). So I don't really know what do you mean.
